export const crOptions = [
  '8',
  '12',
  '10',
  '7',
  '13',
  '28',
  '15',
  '5',
  '39',
  '0.50',
  '0.13',
  '19',
  '23',
  '20',
  '25',
  '14',
  '0.33',
  '6',
  '18',
  '2',
  '29',
  '37',
  '1',
  '4',
  '9',
  '0.25',
  '21',
  '24',
  '0.17',
  '17',
  '30',
  '35',
  '22',
  '3',
  '13.00',
  '27',
  '11',
  '16',
  '26',
];

export const environmentOptions = [
  'warm rivers or swamps',
  'null',
  'forest or underground',
  'Temperate aquatic',
  'the Abyss',
  'warm jungles or forests',
  'temperate or tropical forests, oceans, and rivers',
  'temperate forests and underground',
  'temperate hills, mountains and plains',
  'temperate deserts, hills, or mountains',
  'any (Limbo)',
  'tropical forests',
  'lower planes (usually Nine Hells)',
  'any (Plane of Air or Plane of Fire)',
  'any warm saltwater',
  'temperate or warm islands',
  'cold or temperate mountains',
  'warm coasts',
  'temperate plains, rocky hills, and underground',
  'any sky (Plane of Air)',
  'any forest or jungle (Prime Material Plane)',
  'cold plains, hills, or desert',
  'temperate or warm marshes and aquatic',
  'cold mountains or forests',
  'any (Elemental Plane of Air)',
  'temperate forest, mountains and plains',
  'temperate forests or underground',
  'any (Elemental Plane of Fire)',
  'temperate and warm land',
  'any (Plane of Fire)',
  'temperate forests and urban',
  'cold plains or mountains',
  'Any aquatic',
  'tropical coasts and rivers',
  'any (Ivory Labyrinth)',
  'temperate marshes or underground',
  'temperate lakes or rivers',
  'temperate or warm swamps',
  'temperate or cold hills',
  'temperate and warm water, and underground',
  'any',
  'any aquatic',
  'any (Elemental Plane of Earth, Elemental Plane of Fire, Plane of Molten Skies)',
  'temperate marshes, hills, or coasts',
  'any air (Nirvana)',
  'warm hills and mountains',
  'any temperate, warm, or urban',
  'temperate and warm marshes',
  'any temperate or warm land',
  'any (Ethereal Plane)',
  'any (graveyards, mausoleums, cemeteries)',
  'tropical swamps',
  'warm marshes or rivers',
  'temperate forest',
  'warm rivers',
  'temperate hills and plains',
  'any (Kurnugia)',
  'temperate forests and plains',
  'any (lower planes)',
  'temperate or warm forests',
  'Abyss, Gehenna, Hades, Nine Hells, or Tarterus',
  'temperate mountains or hills',
  'temperate forest or plains',
  'any liquid-based outer or inner plane',
  'any forests or swamps',
  'cold ruins',
  'warm desert and hills',
  'any (Elemental Plane of Earth)',
  'temperate or warm deserts or forests',
  'cold marshes and underground',
  'any swamps or underground',
  'any land and underground, lower planes',
  'any (primal land of fey)',
  'cold lakes and swamps',
  'temperate forest or marshes',
  'any (Hell)',
  'any (usually tombs)',
  'Sea of Fire (Plane of Fire and Plane of Molten Skies) Sea of Fire (Plane of Fire and Plane of Molten Skies)',
  'temperate and warm coastlines and underground',
  'any mountains',
  'warm oceans',
  'temperate mountain valleys',
  'temperate or warm land, aquatic, and underground',
  'warm or temperate deserts, forests, plains, or underground',
  'any temperate or warm forest or plains, or urban',
  'warm marshes',
  'Any',
  'cold forests and mountains',
  'warm forests, oceans, or rivers',
  'Quasi-Plane of Lightning',
  'Temperate or warm aquatic',
  'warm jungles and forests',
  'any warm land',
  'any swamps or woodlands',
  'any water (Nirvana)',
  'any oceans or coastlines',
  'warm forests',
  'warm deserts and hills',
  'Plane of Molten Skies',
  'any land or water (Plane of Water)',
  'any cold land',
  'cold hills and underground',
  'any forests, plains, and swamps',
  'Quasi-Plane of Acid',
  'temperate or warm forests and underground',
  'temperate and warm forest',
  'temperate ruins',
  'temperate or tropical forests or ruins',
  'any lawful evil-aligned plane',
  'any (Hell or Infernus)',
  'any lake or river',
  'temperate plains and forests and underground',
  'any hills or plains',
  'temperate or tropical forests',
  'temperate ruins or underground',
  'temperate plains, hills, or forests',
  'temperate forests or fresh water',
  'cold plains, forests, and marshes',
  'any underground or urban',
  'cold or temperate hills or mountains',
  'temperate forests and marshes',
  'warm or temperate forests',
  'any cold',
  'temperate forests, hills, mountains, or plains',
  'Astral Plane',
  'any (lawful plane)',
  'warm forests or marshes',
  'any (Plane of Air, Plane of Fire, or Plane of Smoke)',
  'any hills',
  'any coastal',
  'warm ruins',
  'temperate and warm plains',
  'warm lakes and rivers',
  'cold mountains or any',
  'cold or temperate forests and plains',
  'any (Nirvana)',
  'any (Purgatory)',
  'any (Positive Energy Plane)',
  'Plane of Fire',
  'temperate mountains and underground',
  'any (Spellscar Desert)',
  'any urban or plains',
  'any land (Plane of Earth)',
  'temperate or warm coastlines or forests',
  'warm lakes, rivers, or swamps',
  'any warm or hot',
  'warm forests or hills',
  'warm hills or mountains',
  'warm forest and mountains',
  'any evil-aligned plane',
  'Elemental Plane of Air',
  'warm plains and forests',
  'temperate marshes or plains',
  'any forests',
  'any rivers',
  'Northlands forests and plains',
  'ocean',
  'temperate mountains',
  'any aquatic (Plane of Water)',
  'cold plains and underground',
  'any (Elysium)',
  'temperate forests or mountains',
  'any warm land and underground',
  'temperate or warm marshes',
  'outer space or cold forest',
  'any good-aligned plane',
  'any underground',
  'any underground (Plane of Earth)',
  'warm plains or deserts (the Mana Wastes)',
  'temperate forest and hills',
  'temperate hills or mountains',
  'any except true neutral',
  'temperate or warm hills or mountains',
  'warm and temperate fresh water and swamps',
  'temperate or warm water',
  'any land (Plane of Shadow)',
  'temperate or tropical hills',
  'temperate deserts',
  'any (Aucturn)',
  'temperate hills, mountains, or underground',
  'any coastlines',
  'cold lands',
  'temperate forest, swamp, or underground',
  'any (Shadow Plane)',
  'any freshwater',
  'temperate and warm mountains',
  'warm rivers (Garund)',
  'any (Plane of Shadow)',
  'underground and temperate marshes',
  'any coastlines or water',
  'any temperate and warm and underground',
  'any mountains or underground (Plane of Fire)',
  'temperate freshwater',
  'Positive Energy Plane',
  'any oceans (Abyss)',
  'temperate hills or plains',
  'swamp or underground',
  'any (Quantium)',
  'temperate or cold aquatic',
  'warm mountains or deserts',
  'temperate forests',
  'warm coastal regions',
  'marshes',
  'warm or temperate land or underground',
  'any land (Elysium)',
  'temperate coastlines',
  'temperate and warm deserts',
  'cold forests or mountains',
  'any temperate or warm',
  'astral plane',
  'any (Elemental Plane of Air or Quasi- Elemental Plane of Lightning)',
  'any (Castrovel)',
  'any (the Abyss)',
  'any (Plane of Air)',
  'warm or temperate oceans',
  'Sea of Fire (Elemental Plane of Fire or Plane of Molten Skies)',
  'any (Hell or Ethereal Plane)',
  'temperate and warm forests and underground',
  'cold or temperate hills',
  'any land (Field of Maidens)',
  'Aballon',
  'any (Nex)',
  'temperate hills, plains, or forests',
  'cold forests or plains',
  'cold plains, hills and mountains',
  'warm deserts or underground',
  'temperate plains',
  'any ruins',
  'urban',
  'temperate plains or forests',
  'warm hills',
  'any hills or forests',
  'tropical hills and mountains',
  'cold aquatic or underground',
  'temperate or cold forests',
  'warm forests or plains',
  'temperate and warm forests and aquatic',
  'cold oceans',
  'temperate forests, hills, or mountains',
  'tropical jungles',
  'underground',
  'warm deserts or mountains',
  'warm or temperate water or coastlines',
  'any (Nine Hells)',
  'temperate and warm forests and marshes',
  'temperate or warm hills',
  'warm land',
  'any swamps',
  'temperate plains or hills',
  'temperate or warm oceans or coastlines',
  'cold lakes, plains, or oceans',
  'cold forest and plains',
  'temperate forests and hills',
  'temperate swamps or underground',
  'warm jungles and swamps',
  'temperate coast or forest',
  'temperate or cold forests and marshes',
  'warm plains or coastlines',
  'Quasi-Elemental Plane of Lightning',
  'cold forests',
  'warm forests, hills, mountains, and plains',
  'cold or temperate coasts, hills, or marshes',
  'any temperate',
  'warm and temperate plains',
  'warm deserts, plains, or hills',
  'temperate rivers or streams',
  "any (R'lyeh)",
  'any oceans',
  'any (Tarterus)',
  'temperate skies, hills, and mountains',
  'warm aquatic',
  'warm forests and plains or underground',
  'warm deserts',
  'cold plains and hills',
  'temperate and warm forests and swamps',
  'any plains or forests',
  'Hades',
  'Inner and Outer planes',
  'underground or temperate and warm swamps',
  'warm plains and underground',
  'any water',
  'temperate hills and underground',
  'temperate forests, hills, and mountains',
  'temperate and warm marshes and underground',
  'temperate hills and ruins',
  'cold or temperate water (waterfalls)',
  'temperate and warm aquatic',
  'temperate or warm aquatic',
  'temperate or warm ocean or coastline',
  'any oceans (during storms)',
  'temperate and warm lands and underground',
  'warm hills or plains',
  'temperate and warm marshes and rivers',
  'River Styx',
  'warm forests or swamps',
  'any land (lawful plane)',
  'any land (usually jungles or underground)',
  'any Outer Plane (Abaddon)',
  'warm forests and marshes',
  'cold and temperate forests, hills and plains',
  'warm aquatic and plains',
  'Hell',
  'any land',
  'cold coastlines and plains',
  'temperate and warm hills and mountains',
  'temperate and warm forests, underground, and urban',
  'any urban or ruins',
  'any forests or plains',
  'warm plains (Nuat)',
  'any warm',
  'Elemental Plane of Fire',
  'any hills or mountains',
  'temperate or warm forests or plains',
  'Nine Hells',
  'warm plains and shorelines',
  'temperate or warm plains',
  'cold deserts and glaciers',
  'any (extraplanar)',
  'warm hills and deserts',
  'temperate and warm forest and underground',
  'cold hills and moutains',
  'Gehenna, Hades, or Tarterus',
  'temperate or warm forests or coasts',
  'temperate and warm forests',
  'temperate or warm deserts or plains',
  'any marsh',
  'temperate and warm forest, hill, marsh, and plains',
  "warm jungles (Yoha's Graveyard)",
  'any deserts or oceans',
  'cold mountains',
  'cold rivers',
  'any (Heaven)',
  'any mountains or underground',
  'any forest or plain (Elysium)',
  'warm or temperate aquatic',
  'temperate forests and plains or underground',
  'warm desert',
  'warm marshes and aquatic',
  'temperate plains and underground',
  'any underground (beneath Kaer Maga)',
  'warm forests and swamps',
  'temperate or warm swamps or underground',
  'Plane of Molten Skies, Elemental Plane of Fire',
  'any rivers or marshes',
  'any (Worldwound)',
  'temperate desert',
  'temperate islands',
  'any (Astral Plane)',
  'warm jungle',
  'warm coastline, swamps, or plains',
  'any temperate land',
  'any underground (except water)',
  'any (Vista)',
  'temperate or warm forest or underground',
  'any (Korvosa)',
  'any water or coastlines',
  'temperate forests and mountains',
  'any blighted land',
  'any ruins or underground',
  'any tropical (First World)',
  'Outer Planes',
  'any (Quasi-Elemental Plane of Lightning)',
  'Limbo',
  'any (Plane of Air or Plane of Water)',
  'any saltwater',
  'any aquatic or land',
  'warm forests or underground',
  'any (usually Gehenna, Hades, or Tarterus)',
  'warm jungles (Mwangi Expanse)',
  'elemental plane of fire',
  'cold and temperate aquatic',
  'temperate or tropical forests or hills',
  'any wastelands',
  'any land (Irrisen)',
  'Plane of Air',
  'temperate or cold ocean',
  'any (Abyss; volcanic regions)',
  'tropical forests (Mediogalti Island)',
  'any land, aquatic, and underground',
  'any non-cold',
  'cold deserts or mountains',
  'temperate hills or underground',
  'any waters (Nirvana)',
  'temperate plains and forests',
  'any ocean',
  'any land or underground near cities',
  'any forest and hills',
  'warm coastline',
  'temperate swamps',
  'temperate underground or marshes',
  'any land (Nirvana)',
  'any land (extraplanar)',
  'outer planes',
  'temperate oceans',
  'warm forests (Abyss)',
  'any (Abaddon)',
  'volcanic underground',
  'warm swamps',
  'warm plains or hills',
  'Elemental Plane of Earth',
  'temperate forests, hills, or plains (pumpkin patches)',
  'temperate lakes, rivers, or swamps',
  'cold or temperate water or underground',
  'temperate mountains and coastal islands',
  'Para-Elemental Plane of Heat',
  'warm rivers or marshes',
  'temperate underground or deep forest',
  'any (Darklands)',
  'cold volcanic mountains',
  'Plane of Time',
  'Elemental Plane of Fire or Plane of Molten Skies',
  'temperate forests or plains',
  'temperate and warm deserts and mountains',
  'temperate or warm ocean',
  'Any forest, hills, plains, and mountains',
  'any forest, hill, jungle, or plains',
  'any (see text)',
  'tropical rivers and lakes',
  'any forests (primal land of fey)',
  'any land or urban',
  'any terrestrial vacuum',
  'forests or jungle',
  'any (Negative Energy Plane)',
  'warm hills and marshes',
  'any swamp',
  'warm islands',
  'temperate and cold forests',
  'Quasi-Plane of Obsidian',
  'warm lakes',
  'warm forests and mountains',
  'warm forests and hills',
  'temperate marshes',
  'temperate or warm rivers',
  'any oceans and underground',
  'temperate water',
  'any temperate and warm land',
  'any cold (Abyss)',
  'any (Material Plane only)',
  'Plane of Earth',
  'any aboveground natural area',
  'warm forests, hills, or mountains',
  'any (Outer Planes)',
  'warm ocean or coastline',
  'Plane of Slime',
  'any land or water',
  'temperate swamp',
  'warm forests, hills, or plains',
  'any (Plane of Molten Skies)',
  'cold hills',
  'cold hills and mountains',
  'any (underground)',
  'any forest',
  'warm forest and aquatic',
  'any cold or temperate land',
  'cold hills, mountains, or plains',
  'any volcano or underground',
  'temperate forests, marshes, and urban',
  'temperate hills',
  'see text',
  'temperate and hot plains or urban',
  'temperate or warm oceans',
  'any (Casmaron)',
  'warm deserts or hills',
  'any temperate and warm',
  'temperate lakes or swamps',
  'warm coastline or forest',
  'any land or underground (Plane of Shadow)',
  'warm water',
  'warm rivers and marshes',
  'any land (Plane of Fire)',
  'aquatic',
  'any plains or swamps',
  'any (Infernus)',
  'any mountain',
  'Negative Energy Plane',
  'temperate forests or jungles',
  'cold swamps or coastlines',
  'warm coasts and oceans',
  'temperate or warm forests or swamps',
  'warm plains or desert',
  'warm mountains',
  'Elysium',
  'Plane of Shadow',
  'cold and temperate forests, marshes and plains',
  'underground or temperate forest',
  'warm forests, swamps, and fresh water',
  'warm deserts or urban',
  'warm deserts or islands',
  'temperate hills and mountains',
  'cold forest or mountains',
  'temperate coasts',
  'cold coastlines',
  'temperate rivers or lakes',
  'Plane of Water',
  'any underground (Darklands)',
  'any (the Boneyard)',
  'cold forests and plains',
  'Temperate Forests',
  'Elemental Plane of Time',
  'warm plains',
  'any urban or underground',
  'cold coastlines, hills, or plains',
  'temperate forest or swamp',
  'temperate marshes and underground',
  'any (Abyss; battlefields and graveyards)',
  'any land (evil Outer Plane)',
  'temperate or warm forests, hills, or underground',
  'any forests or mountains (Nirvana)',
  'cold hills or glaciers',
  'temperate aquatic',
  'temperate land',
  'any land (Hell)',
  'temperate and warm swamps',
  'cold mountains or underground',
  'any (usually underground)',
  'any relatively flat and dry terrain',
  'any freshwater aquatic',
  'temperate and warm oceans',
  'any lakes',
  'underground (the Bloodways)',
  'temperate mountains or urban',
  'warm deserts, hills, or plains',
  'temperate and hot forests and deserts',
  'Quasi-Plane of Vapor',
  'temperate forests or hills',
  'temperate or cold aquatic or underground',
  'cold mountainous coastlines',
  'warm forest and plains',
  'any marshes or underground',
  'cold or temperate plains',
  'any battle',
  'temperate or warm forest',
  'cold and temperate forests and plains',
  'any temperate or warm aquatic',
  'warm or temperate plains',
  'tropical oceans',
  'any sky',
  'temperate or tropical swamps',
  'warm forest',
  'any swamp or underground',
  'vacuum',
  'temperate forests (The Hollow Mountain)',
  'warm mountains or underground',
  'any swamp (Abyss)',
  'warm subterranean lakes and rivers',
  'any (evil planes)',
  'temperate or warm jungles',
  'any tropical',
  'any (usually Gehenna, Tarterus, or Hades)',
  'any underground or swamps',
  'temperate forests or urban',
  'any (Abaddon or Astral Plane)',
  'temperate and warm plains or desert',
  'temperate or warm water or shore',
  'any land and underground',
  'any (Plane of Earth)',
  'any forests or hills',
  'cold plains',
  'any mountains (Dimension of Dreams)',
  'temperate or cold hills or underground',
  'cold or temperate forests and mountains',
  'cold forests, hills, mountains and plains',
  'any ocean or coastline',
  'cold and temperate oceans',
  'any evil-aligned planes',
  'any temperate or underground',
  'warm mountains and underground',
  'cold or temperate forest and plains',
  'warm coasts or forests',
  'temperate forest and plains (usually coastal regions)',
  'any forest or hill',
  'any underground (the Abyss)',
  'The Abyss',
  'temperate ocean',
  'temperate or warm land',
  'cold swamps',
  'any land (Abaddon)',
  'temperate marsh',
  'warm plains and deserts',
  'any land (graveyards and cemeteries)',
  'any temperate and warm land and underground',
  'warm forest, plains, or hills',
  'temperate or warm marshes or underground',
  'any (graveyards or the Boneyard)',
  'warm fresh water',
  'Plane of Molten Skies or Elemental Plane of Fire',
  'any water (Plane of Water)',
  'temperate forests, plains, or swamps',
  'cold and temperate forests',
  'tropical jungles (Mediogalti Island)',
  'warm forests or mountains',
  'Plane of Gravity',
  'warm forests and plains',
  'any (the Worldwound)',
  'temperate or warm forests or underground',
  'any temperate or tropical',
  'warm deserts or plains',
  'any (haunted sites or ruins)',
  'cold plains, hills, or mountains',
  'gas giants or vacuum',
  'any (River Styx)',
  'warm oceans or coastlines',
  'any land or sky (lightning storms)',
  'any (Sekatar-Seraktis)',
  'warm rivers, lakes, and swamps',
  'temperate or warm forests and marshes',
  'any land or underground',
  'tropical forests and jungles',
  'temperate forest and mountain',
  'any (Ghahazi, Abyss)',
  'any volcanoes or underground',
  'temperate forests or marshes',
  'cold marshes',
  'tropical lakes and rivers',
  'temperate forests, mountains, or underground',
  'any non-cold underground',
  'any marsh or underground',
  'any air',
  'any urban',
  'temperate or warm mountains',
  'any (Abyss)',
  'warm coastlines',
  'any water (coastal)',
  'warm ocean',
  'urban (Abyss)',
  'temperate swamp or underground',
  'any (elemental planes)',
  'any (Plane of Water)',
  'any near ghouls',
  'tropical deserts',
  'any land or water (Plane of Earth)',
  'tropical or temperate forests',
  'cold or temperate forests',
  'temperate forests, lakes, or rivers',
  'warm jungles',
  'cold hills or mountains',
  'any land (Abyss)',
  'temperate mountains (Arcadia)',
];

export const subtypeOptions = [
  'aquatic',
  'ratfolk',
  'clockwork',
  'augmented aberration',
  'orc',
  'swarm',
  'sciruian',
  'shapechanger',
  'fire',
  'gnoll',
  'azata',
  'reptilian',
  'sasquatch',
  'agathion',
  'giant',
  'lashunta',
  'tengu',
  'good',
  'augmented humanoid',
  'changeling',
  'oni',
  'asura',
  'null',
  'elemental',
  'mythic',
  'kuru',
  'wayang',
  'stormwarden',
  'amphibious',
  'lupin',
  'strix',
  'augmented animal',
  'div',
  'varies',
  'dwarf ',
  'behemoth',
  'tabaxi',
  'incorporeal',
  'time',
  'augmented human',
  'ogrillon',
  'water',
  'leshy',
  'horde',
  'archon',
  'earth',
  'extraplanar',
  'kitsune',
  'kasatha',
  'augmented fey',
  'charau-ka',
  'augmented magical beast',
  'kuah-lij',
  'xothotak',
  'skulk',
  'dark folk',
  'samsaran',
  'elf ',
  'colossus',
  'aquatic*',
  'Water',
  'elf',
  'aeon',
  'dhampir',
  'daemon',
  'native',
  'goblinoid',
  'acid',
  'human',
  'vanara',
  'Triaxian',
  'gnome',
  'chaotic',
  'Fire',
  'korog',
  'boggard',
  'devil',
  'angel',
  'air',
  'fungus',
  'cold',
  'vishkanya',
  'derro',
  'psychopomp',
  'ogren',
  'android',
  'kami',
  'syrinx',
  'megaswarm',
  'augmented vermin',
  'adlet',
  'evil',
  'electricity',
  'grippli',
  'catfolk',
];

export const typeOptions = [
  'monstrous humanoid',
  'animal',
  'humanoid',
  'dragon',
  'magical beast',
  'Dragon',
  'aberration',
  'plant',
  'undead',
  'Ooze',
  'fey',
  'outsider',
  'Outsider',
  'ooze',
  'construct',
  'vermin',
];
