export const crOptions = [
  '0.13',
  '0.17',
  '0.25',
  '0.33',
  '0.5',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '13.0',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '21',
  '22',
  '23',
  '24',
  '25',
  '26',
  '27',
  '28',
  '29',
  '30',
  '35',
  '37',
  '39',
];

export const environmentOptions = [
  'Aballon',
  'Abyss, Gehenna, Hades, Nine Hells, or Tarterus',
  'Astral Plane',
  'Elemental Plane of Air',
  'Elemental Plane of Earth',
  'Elemental Plane of Fire',
  'Elemental Plane of Fire or Plane of Molten Skies',
  'Elemental Plane of Time',
  'Elysium',
  'Gehenna, Hades, or Tarterus',
  'Hades',
  'Hell',
  'Inner and Outer planes',
  'Limbo',
  'Negative Energy Plane',
  'Nine Hells',
  'Northlands forests and plains',
  'Outer Planes',
  'Para-Elemental Plane of Heat',
  'Plane of Air',
  'Plane of Earth',
  'Plane of Fire',
  'Plane of Gravity',
  'Plane of Molten Skies',
  'Plane of Molten Skies or Elemental Plane of Fire',
  'Plane of Molten Skies, Elemental Plane of Fire',
  'Plane of Shadow',
  'Plane of Slime',
  'Plane of Time',
  'Plane of Water',
  'Positive Energy Plane',
  'Quasi-Elemental Plane of Lightning',
  'Quasi-Plane of Acid',
  'Quasi-Plane of Lightning',
  'Quasi-Plane of Obsidian',
  'Quasi-Plane of Vapor',
  'River Styx',
  'Sea of Fire (Elemental Plane of Fire or Plane of Molten Skies)',
  'Sea of Fire (Plane of Fire and Plane of Molten Skies) Sea of Fire (Plane of Fire and Plane of Molten Skies)',
  'Temperate Forests',
  'Temperate aquatic',
  'Temperate or warm aquatic',
  'The Abyss',
  'any',
  'any (Abaddon or Astral Plane)',
  'any (Abaddon)',
  'any (Abyss)',
  'any (Abyss; battlefields and graveyards)',
  'any (Abyss; volcanic regions)',
  'any (Astral Plane)',
  'any (Aucturn)',
  'any (Casmaron)',
  'any (Castrovel)',
  'any (Darklands)',
  'any (Elemental Plane of Air or Quasi- Elemental Plane of Lightning)',
  'any (Elemental Plane of Air)',
  'any (Elemental Plane of Earth)',
  'any (Elemental Plane of Earth, Elemental Plane of Fire, Plane of Molten Skies)',
  'any (Elemental Plane of Fire)',
  'any (Elysium)',
  'any (Ethereal Plane)',
  'any (Ghahazi, Abyss)',
  'any (Heaven)',
  'any (Hell or Ethereal Plane)',
  'any (Hell or Infernus)',
  'any (Hell)',
  'any (Infernus)',
  'any (Ivory Labyrinth)',
  'any (Korvosa)',
  'any (Kurnugia)',
  'any (Limbo)',
  'any (Material Plane only)',
  'any (Negative Energy Plane)',
  'any (Nex)',
  'any (Nine Hells)',
  'any (Nirvana)',
  'any (Outer Planes)',
  'any (Plane of Air or Plane of Fire)',
  'any (Plane of Air or Plane of Water)',
  'any (Plane of Air)',
  'any (Plane of Air, Plane of Fire, or Plane of Smoke)',
  'any (Plane of Earth)',
  'any (Plane of Fire)',
  'any (Plane of Molten Skies)',
  'any (Plane of Shadow)',
  'any (Plane of Water)',
  'any (Positive Energy Plane)',
  'any (Purgatory)',
  'any (Quantium)',
  'any (Quasi-Elemental Plane of Lightning)',
  "any (R'lyeh)",
  'any (River Styx)',
  'any (Sekatar-Seraktis)',
  'any (Shadow Plane)',
  'any (Spellscar Desert)',
  'any (Tarterus)',
  'any (Vista)',
  'any (Worldwound)',
  'any (elemental planes)',
  'any (evil planes)',
  'any (extraplanar)',
  'any (graveyards or the Boneyard)',
  'any (graveyards, mausoleums, cemeteries)',
  'any (haunted sites or ruins)',
  'any (lawful plane)',
  'any (lower planes)',
  'any (primal land of fey)',
  'any (see text)',
  'any (the Abyss)',
  'any (the Boneyard)',
  'any (the Worldwound)',
  'any (underground)',
  'any (usually Gehenna, Hades, or Tarterus)',
  'any (usually Gehenna, Tarterus, or Hades)',
  'any (usually tombs)',
  'any (usually underground)',
  'any Outer Plane (Abaddon)',
  'any aboveground natural area',
  'any air',
  'any air (Nirvana)',
  'any aquatic',
  'any aquatic (Plane of Water)',
  'any aquatic or land',
  'any battle',
  'any blighted land',
  'any coastal',
  'any coastlines',
  'any coastlines or water',
  'any cold',
  'any cold (Abyss)',
  'any cold land',
  'any cold or temperate land',
  'any deserts or oceans',
  'any evil-aligned plane',
  'any evil-aligned planes',
  'any except true neutral',
  'any forest',
  'any forest and hills',
  'any forest or hill',
  'any forest or jungle (Prime Material Plane)',
  'any forest or plain (Elysium)',
  'any forest, hill, jungle, or plains',
  'any forest, hills, plains, and mountains',
  'any forests',
  'any forests (primal land of fey)',
  'any forests or hills',
  'any forests or mountains (Nirvana)',
  'any forests or plains',
  'any forests or swamps',
  'any forests, plains, and swamps',
  'any freshwater',
  'any freshwater aquatic',
  'any good-aligned plane',
  'any hills',
  'any hills or forests',
  'any hills or mountains',
  'any hills or plains',
  'any lake or river',
  'any lakes',
  'any land',
  'any land (Abaddon)',
  'any land (Abyss)',
  'any land (Elysium)',
  'any land (Field of Maidens)',
  'any land (Hell)',
  'any land (Irrisen)',
  'any land (Nirvana)',
  'any land (Plane of Earth)',
  'any land (Plane of Fire)',
  'any land (Plane of Shadow)',
  'any land (evil Outer Plane)',
  'any land (extraplanar)',
  'any land (graveyards and cemeteries)',
  'any land (lawful plane)',
  'any land (usually jungles or underground)',
  'any land and underground',
  'any land and underground, lower planes',
  'any land or sky (lightning storms)',
  'any land or underground',
  'any land or underground (Plane of Shadow)',
  'any land or underground near cities',
  'any land or urban',
  'any land or water',
  'any land or water (Plane of Earth)',
  'any land or water (Plane of Water)',
  'any land, aquatic, and underground',
  'any lawful evil-aligned plane',
  'any liquid-based outer or inner plane',
  'any marsh',
  'any marsh or underground',
  'any marshes or underground',
  'any mountain',
  'any mountains',
  'any mountains (Dimension of Dreams)',
  'any mountains or underground',
  'any mountains or underground (Plane of Fire)',
  'any near ghouls',
  'any non-cold',
  'any non-cold underground',
  'any ocean',
  'any ocean or coastline',
  'any oceans',
  'any oceans (Abyss)',
  'any oceans (during storms)',
  'any oceans and underground',
  'any oceans or coastlines',
  'any plains or forests',
  'any plains or swamps',
  'any relatively flat and dry terrain',
  'any rivers',
  'any rivers or marshes',
  'any ruins',
  'any ruins or underground',
  'any saltwater',
  'any sky',
  'any sky (Plane of Air)',
  'any swamp',
  'any swamp (Abyss)',
  'any swamp or underground',
  'any swamps',
  'any swamps or underground',
  'any swamps or woodlands',
  'any temperate',
  'any temperate and warm',
  'any temperate and warm and underground',
  'any temperate and warm land',
  'any temperate and warm land and underground',
  'any temperate land',
  'any temperate or tropical',
  'any temperate or underground',
  'any temperate or warm',
  'any temperate or warm aquatic',
  'any temperate or warm forest or plains, or urban',
  'any temperate or warm land',
  'any temperate, warm, or urban',
  'any terrestrial vacuum',
  'any tropical',
  'any tropical (First World)',
  'any underground',
  'any underground (Darklands)',
  'any underground (Plane of Earth)',
  'any underground (beneath Kaer Maga)',
  'any underground (except water)',
  'any underground (the Abyss)',
  'any underground or swamps',
  'any underground or urban',
  'any urban',
  'any urban or plains',
  'any urban or ruins',
  'any urban or underground',
  'any volcano or underground',
  'any volcanoes or underground',
  'any warm',
  'any warm land',
  'any warm land and underground',
  'any warm or hot',
  'any warm saltwater',
  'any wastelands',
  'any water',
  'any water (Nirvana)',
  'any water (Plane of Water)',
  'any water (coastal)',
  'any water or coastlines',
  'any waters (Nirvana)',
  'aquatic',
  'astral plane',
  'cold and temperate aquatic',
  'cold and temperate forests',
  'cold and temperate forests and plains',
  'cold and temperate forests, hills and plains',
  'cold and temperate forests, marshes and plains',
  'cold and temperate oceans',
  'cold aquatic or underground',
  'cold coastlines',
  'cold coastlines and plains',
  'cold coastlines, hills, or plains',
  'cold deserts and glaciers',
  'cold deserts or mountains',
  'cold forest and plains',
  'cold forest or mountains',
  'cold forests',
  'cold forests and mountains',
  'cold forests and plains',
  'cold forests or mountains',
  'cold forests or plains',
  'cold forests, hills, mountains and plains',
  'cold hills',
  'cold hills and mountains',
  'cold hills and moutains',
  'cold hills and underground',
  'cold hills or glaciers',
  'cold hills or mountains',
  'cold hills, mountains, or plains',
  'cold lakes and swamps',
  'cold lakes, plains, or oceans',
  'cold lands',
  'cold marshes',
  'cold marshes and underground',
  'cold mountainous coastlines',
  'cold mountains',
  'cold mountains or any',
  'cold mountains or forests',
  'cold mountains or underground',
  'cold oceans',
  'cold or temperate coasts, hills, or marshes',
  'cold or temperate forest and plains',
  'cold or temperate forests',
  'cold or temperate forests and mountains',
  'cold or temperate forests and plains',
  'cold or temperate hills',
  'cold or temperate hills or mountains',
  'cold or temperate mountains',
  'cold or temperate plains',
  'cold or temperate water (waterfalls)',
  'cold or temperate water or underground',
  'cold plains',
  'cold plains and hills',
  'cold plains and underground',
  'cold plains or mountains',
  'cold plains, forests, and marshes',
  'cold plains, hills and mountains',
  'cold plains, hills, or desert',
  'cold plains, hills, or mountains',
  'cold rivers',
  'cold ruins',
  'cold swamps',
  'cold swamps or coastlines',
  'cold volcanic mountains',
  'elemental plane of fire',
  'forest or underground',
  'forests or jungle',
  'gas giants or vacuum',
  'lower planes (usually Nine Hells)',
  'marshes',
  'null',
  'ocean',
  'outer planes',
  'outer space or cold forest',
  'see text',
  'swamp or underground',
  'temperate and cold forests',
  'temperate and hot forests and deserts',
  'temperate and hot plains or urban',
  'temperate and warm aquatic',
  'temperate and warm coastlines and underground',
  'temperate and warm deserts',
  'temperate and warm deserts and mountains',
  'temperate and warm forest',
  'temperate and warm forest and underground',
  'temperate and warm forest, hill, marsh, and plains',
  'temperate and warm forests',
  'temperate and warm forests and aquatic',
  'temperate and warm forests and marshes',
  'temperate and warm forests and swamps',
  'temperate and warm forests and underground',
  'temperate and warm forests, underground, and urban',
  'temperate and warm hills and mountains',
  'temperate and warm land',
  'temperate and warm lands and underground',
  'temperate and warm marshes',
  'temperate and warm marshes and rivers',
  'temperate and warm marshes and underground',
  'temperate and warm mountains',
  'temperate and warm oceans',
  'temperate and warm plains',
  'temperate and warm plains or desert',
  'temperate and warm swamps',
  'temperate and warm water, and underground',
  'temperate aquatic',
  'temperate coast or forest',
  'temperate coastlines',
  'temperate coasts',
  'temperate desert',
  'temperate deserts',
  'temperate deserts, hills, or mountains',
  'temperate forest',
  'temperate forest and hills',
  'temperate forest and mountain',
  'temperate forest and plains (usually coastal regions)',
  'temperate forest or marshes',
  'temperate forest or plains',
  'temperate forest or swamp',
  'temperate forest, mountains and plains',
  'temperate forest, swamp, or underground',
  'temperate forests',
  'temperate forests (The Hollow Mountain)',
  'temperate forests and hills',
  'temperate forests and marshes',
  'temperate forests and mountains',
  'temperate forests and plains',
  'temperate forests and plains or underground',
  'temperate forests and underground',
  'temperate forests and urban',
  'temperate forests or fresh water',
  'temperate forests or hills',
  'temperate forests or jungles',
  'temperate forests or marshes',
  'temperate forests or mountains',
  'temperate forests or plains',
  'temperate forests or underground',
  'temperate forests or urban',
  'temperate forests, hills, and mountains',
  'temperate forests, hills, mountains, or plains',
  'temperate forests, hills, or mountains',
  'temperate forests, hills, or plains (pumpkin patches)',
  'temperate forests, lakes, or rivers',
  'temperate forests, marshes, and urban',
  'temperate forests, mountains, or underground',
  'temperate forests, plains, or swamps',
  'temperate freshwater',
  'temperate hills',
  'temperate hills and mountains',
  'temperate hills and plains',
  'temperate hills and ruins',
  'temperate hills and underground',
  'temperate hills or mountains',
  'temperate hills or plains',
  'temperate hills or underground',
  'temperate hills, mountains and plains',
  'temperate hills, mountains, or underground',
  'temperate hills, plains, or forests',
  'temperate islands',
  'temperate lakes or rivers',
  'temperate lakes or swamps',
  'temperate lakes, rivers, or swamps',
  'temperate land',
  'temperate marsh',
  'temperate marshes',
  'temperate marshes and underground',
  'temperate marshes or plains',
  'temperate marshes or underground',
  'temperate marshes, hills, or coasts',
  'temperate mountain valleys',
  'temperate mountains',
  'temperate mountains (Arcadia)',
  'temperate mountains and coastal islands',
  'temperate mountains and underground',
  'temperate mountains or hills',
  'temperate mountains or urban',
  'temperate ocean',
  'temperate oceans',
  'temperate or cold aquatic',
  'temperate or cold aquatic or underground',
  'temperate or cold forests',
  'temperate or cold forests and marshes',
  'temperate or cold hills',
  'temperate or cold hills or underground',
  'temperate or cold ocean',
  'temperate or tropical forests',
  'temperate or tropical forests or hills',
  'temperate or tropical forests or ruins',
  'temperate or tropical forests, oceans, and rivers',
  'temperate or tropical hills',
  'temperate or tropical swamps',
  'temperate or warm aquatic',
  'temperate or warm coastlines or forests',
  'temperate or warm deserts or forests',
  'temperate or warm deserts or plains',
  'temperate or warm forest',
  'temperate or warm forest or underground',
  'temperate or warm forests',
  'temperate or warm forests and marshes',
  'temperate or warm forests and underground',
  'temperate or warm forests or coasts',
  'temperate or warm forests or plains',
  'temperate or warm forests or swamps',
  'temperate or warm forests or underground',
  'temperate or warm forests, hills, or underground',
  'temperate or warm hills',
  'temperate or warm hills or mountains',
  'temperate or warm islands',
  'temperate or warm jungles',
  'temperate or warm land',
  'temperate or warm land, aquatic, and underground',
  'temperate or warm marshes',
  'temperate or warm marshes and aquatic',
  'temperate or warm marshes or underground',
  'temperate or warm mountains',
  'temperate or warm ocean',
  'temperate or warm ocean or coastline',
  'temperate or warm oceans',
  'temperate or warm oceans or coastlines',
  'temperate or warm plains',
  'temperate or warm rivers',
  'temperate or warm swamps',
  'temperate or warm swamps or underground',
  'temperate or warm water',
  'temperate or warm water or shore',
  'temperate plains',
  'temperate plains and forests',
  'temperate plains and forests and underground',
  'temperate plains and underground',
  'temperate plains or forests',
  'temperate plains or hills',
  'temperate plains, hills, or forests',
  'temperate plains, rocky hills, and underground',
  'temperate rivers or lakes',
  'temperate rivers or streams',
  'temperate ruins',
  'temperate ruins or underground',
  'temperate skies, hills, and mountains',
  'temperate swamp',
  'temperate swamp or underground',
  'temperate swamps',
  'temperate swamps or underground',
  'temperate underground or deep forest',
  'temperate underground or marshes',
  'temperate water',
  'the Abyss',
  'tropical coasts and rivers',
  'tropical deserts',
  'tropical forests',
  'tropical forests (Mediogalti Island)',
  'tropical forests and jungles',
  'tropical hills and mountains',
  'tropical jungles',
  'tropical jungles (Mediogalti Island)',
  'tropical lakes and rivers',
  'tropical oceans',
  'tropical or temperate forests',
  'tropical rivers and lakes',
  'tropical swamps',
  'underground',
  'underground (the Bloodways)',
  'underground and temperate marshes',
  'underground or temperate and warm swamps',
  'underground or temperate forest',
  'urban',
  'urban (Abyss)',
  'vacuum',
  'volcanic underground',
  'warm and temperate fresh water and swamps',
  'warm and temperate plains',
  'warm aquatic',
  'warm aquatic and plains',
  'warm coastal regions',
  'warm coastline',
  'warm coastline or forest',
  'warm coastline, swamps, or plains',
  'warm coastlines',
  'warm coasts',
  'warm coasts and oceans',
  'warm coasts or forests',
  'warm desert',
  'warm desert and hills',
  'warm deserts',
  'warm deserts and hills',
  'warm deserts or hills',
  'warm deserts or islands',
  'warm deserts or mountains',
  'warm deserts or plains',
  'warm deserts or underground',
  'warm deserts or urban',
  'warm deserts, hills, or plains',
  'warm deserts, plains, or hills',
  'warm forest',
  'warm forest and aquatic',
  'warm forest and mountains',
  'warm forest and plains',
  'warm forest, plains, or hills',
  'warm forests',
  'warm forests (Abyss)',
  'warm forests and hills',
  'warm forests and marshes',
  'warm forests and mountains',
  'warm forests and plains',
  'warm forests and plains or underground',
  'warm forests and swamps',
  'warm forests or hills',
  'warm forests or marshes',
  'warm forests or mountains',
  'warm forests or plains',
  'warm forests or swamps',
  'warm forests or underground',
  'warm forests, hills, mountains, and plains',
  'warm forests, hills, or mountains',
  'warm forests, hills, or plains',
  'warm forests, oceans, or rivers',
  'warm forests, swamps, and fresh water',
  'warm fresh water',
  'warm hills',
  'warm hills and deserts',
  'warm hills and marshes',
  'warm hills and mountains',
  'warm hills or mountains',
  'warm hills or plains',
  'warm islands',
  'warm jungle',
  'warm jungles',
  'warm jungles (Mwangi Expanse)',
  "warm jungles (Yoha's Graveyard)",
  'warm jungles and forests',
  'warm jungles and swamps',
  'warm jungles or forests',
  'warm lakes',
  'warm lakes and rivers',
  'warm lakes, rivers, or swamps',
  'warm land',
  'warm marshes',
  'warm marshes and aquatic',
  'warm marshes or rivers',
  'warm mountains',
  'warm mountains and underground',
  'warm mountains or deserts',
  'warm mountains or underground',
  'warm ocean',
  'warm ocean or coastline',
  'warm oceans',
  'warm oceans or coastlines',
  'warm or temperate aquatic',
  'warm or temperate deserts, forests, plains, or underground',
  'warm or temperate forests',
  'warm or temperate land or underground',
  'warm or temperate oceans',
  'warm or temperate plains',
  'warm or temperate water or coastlines',
  'warm plains',
  'warm plains (Nuat)',
  'warm plains and deserts',
  'warm plains and forests',
  'warm plains and shorelines',
  'warm plains and underground',
  'warm plains or coastlines',
  'warm plains or desert',
  'warm plains or deserts (the Mana Wastes)',
  'warm plains or hills',
  'warm rivers',
  'warm rivers (Garund)',
  'warm rivers and marshes',
  'warm rivers or marshes',
  'warm rivers or swamps',
  'warm rivers, lakes, and swamps',
  'warm ruins',
  'warm subterranean lakes and rivers',
  'warm swamps',
  'warm water',
];

export const subtypeOptions = [
  'Acid',
  'Adlet',
  'Aeon',
  'Agathion',
  'Air',
  'Amphibious',
  'Android',
  'Angel',
  'Aquatic',
  'Aquatic*',
  'Archon',
  'Asura',
  'Augmented Aberration',
  'Augmented Animal',
  'Augmented Fey',
  'Augmented Human',
  'Augmented Humanoid',
  'Augmented Magical Beast',
  'Augmented Vermin',
  'Azata',
  'Behemoth',
  'Boggard',
  'Catfolk',
  'Changeling',
  'Chaotic',
  'Charau-Ka',
  'Clockwork',
  'Cold',
  'Colossus',
  'Daemon',
  'Dark Folk',
  'Derro',
  'Devil',
  'Dhampir',
  'Div',
  'Dwarf ',
  'Earth',
  'Electricity',
  'Elemental',
  'Elf',
  'Elf ',
  'Evil',
  'Extraplanar',
  'Fire',
  'Fsciruian',
  'Fungus',
  'Giant',
  'Gnoll',
  'Gnome',
  'Goblinoid',
  'Good',
  'Grippli',
  'Horde',
  'Human',
  'Incorporeal',
  'Kami',
  'Kasatha',
  'Kitsune',
  'Korog',
  'Kuah-Lij',
  'Kuru',
  'Lashunta',
  'Leshy',
  'Lupin',
  'Megaswarm',
  'Mythic',
  'Native',
  'Null',
  'Ogren',
  'Ogrillon',
  'Oni',
  'Orc',
  'Psychopomp',
  'Ratfolk',
  'Reptilian',
  'Samsaran',
  'Sasquatch',
  'Shapechanger',
  'Skulk',
  'Stormwarden',
  'Strix',
  'Swarm',
  'Syrinx',
  'Tabaxi',
  'Tengu',
  'Time',
  'Triaxian',
  'Vanara',
  'Varies',
  'Vishkanya',
  'Water',
  'Wayang',
  'Xothotak',
];

export const typeOptions = [
  'Aberration',
  'Animal',
  'Construct',
  'Dragon',
  'Fey',
  'Humanoid',
  'Magical Beast',
  'Monstrous Humanoid',
  'Ooze',
  'Outsider',
  'Plant',
  'Undead',
  'Vermin',
];
