require 'csv'

csv_text = File.read(Rails.root.join('lib', 'tasks', 'seeds', 'Bestiary.csv'))
csv = CSV.parse(csv_text, :headers => true, :encoding => 'ISO-8859-1')
puts csv
csv.each do |row|
    t = Creature.new
    t.name = row['Name']
    t.cr = row['CR']
    t.xp = row['XP']
    t.race = row['Race']
    t.class1 = row['Class1']
    t.class1_lvl = row['Class1_Lvl']
    t.class2 = row['Class2']
    t.class2_lvl = row['Class2_Lvl']
    t.alignment = row['Alignment']
    t.size = row['Size']
    t.maintype = row['Type']
    t.subtype1 = row['subtype1']
    t.subtype2 = row['subtype2']
    t.subtype3 = row['subtype3']
    t.subtype4 = row['subtype4']
    t.subtype5 = row['subtype5']
    t.subtype6 = row['subtype6']
    t.ac = row['AC']
    t.ac_touch = row['AC_Touch']
    t.ac_flat_footed = row['AC_Flat-Footed']
    t.hp = row['HP']
    t.hd = row['HD']
    t.fort = row['Fort']
    t.ref = row['Ref']
    t.will = row['Will']
    t.melee = row['Melee']
    t.ranged = row['Ranged']
    t.space = row['Space']
    t.reach = row['Reach']
    t.str = row['Str']
    t.dex = row['Dex']
    t.con = row['Con']
    t.int = row['Int']
    t.wis = row['Wis']
    t.cha = row['Cha']
    t.feats = row['Feats']
    t.skills = row['Skills']
    t.racial_mods = row['RacialMods']
    t.languages = row['Languages']
    t.sq = row['SQ']
    t.environment = row['Environment']
    t.organization = row['Organization']
    t.treasure = row['Treasure']
    t.group = row['Group']
    t.gear = row['Gear']
    t.other_gear = row['OtherGear']
    t.character_flag = row['CharacterFlag']
    t.companion_flag = row['CompanionFlag']
    t.speed = row['Speed']
    t.base_speed = row['Base_Speed']
    t.fly_speed = row['Fly_Speed']
    t.maneuverability = row['Maneuverability']
    t.climb_speed = row['Climb_Speed']
    t.swim_speed = row['Swim_Speed']
    t.burrow_speed = row['Burrow_Speed']
    t.speed_special = row['Speed_Special']
    t.speed_land = row['Speed_Land']
    t.save
    puts "#{t.name} saved"
end
puts "There are now #{Creature.count} rows in the Creature table."

