class CreateCreatures < ActiveRecord::Migration[7.0]
  def change
    create_table :creatures do |t|
      t.string :name
      t.string :cr
      t.string :xp
      t.string :race
      t.string :class1
      t.string :class1_lvl
      t.string :class2
      t.string :class2_lvl
      t.string :alignment
      t.string :size
      t.string :maintype
      t.string :subtype1
      t.string :subtype2
      t.string :subtype3
      t.string :subtype4
      t.string :subtype5
      t.string :subtype6
      t.string :ac
      t.string :ac_touch
      t.string :ac_flat_footed
      t.string :hp
      t.string :hd
      t.string :fort
      t.string :ref
      t.string :will
      t.string :melee
      t.string :ranged
      t.string :space
      t.string :reach
      t.string :str
      t.string :dex
      t.string :con
      t.string :int
      t.string :wis
      t.string :cha
      t.string :feats
      t.string :skills
      t.string :racial_mods
      t.string :languages
      t.string :sq
      t.string :environment
      t.string :organization
      t.string :treasure
      t.string :group
      t.string :gear
      t.string :other_gear
      t.string :character_flag
      t.string :companion_flag
      t.string :speed
      t.string :base_speed
      t.string :fly_speed
      t.string :maneuverability
      t.string :climb_speed
      t.string :swim_speed
      t.string :burrow_speed
      t.string :speed_special
      t.string :speed_land
      t.string :timestamps
    end
  end
end
