function Environment({ onEnvironmentChange }) {
  let environmentOptions = [
    { id: 0, name: 'warm rivers or swamps' },
    { id: 1, name: 'null' },
    { id: 2, name: 'forest or underground' },
    { id: 3, name: 'Temperate aquatic' },
    { id: 4, name: 'the Abyss' },
    { id: 5, name: 'warm jungles or forests' },
    { id: 6, name: 'temperate or tropical forests, oceans, and rivers' },
    { id: 7, name: 'temperate forests and underground' },
    { id: 8, name: 'temperate hills, mountains and plains' },
    { id: 9, name: 'temperate deserts, hills, or mountains' },
    { id: 10, name: 'any (Limbo)' },
    { id: 11, name: 'tropical forests' },
    { id: 12, name: 'lower planes (usually Nine Hells)' },
    { id: 13, name: 'any (Plane of Air or Plane of Fire)' },
    { id: 14, name: 'any warm saltwater' },
    { id: 15, name: 'temperate or warm islands' },
    { id: 16, name: 'cold or temperate mountains' },
    { id: 17, name: 'warm coasts' },
    { id: 18, name: 'temperate plains, rocky hills, and underground' },
    { id: 19, name: 'any sky (Plane of Air)' },
    { id: 20, name: 'any forest or jungle (Prime Material Plane)' },
    { id: 21, name: 'cold plains, hills, or desert' },
    { id: 22, name: 'temperate or warm marshes and aquatic' },
    { id: 23, name: 'cold mountains or forests' },
    { id: 24, name: 'any (Elemental Plane of Air)' },
    { id: 25, name: 'temperate forest, mountains and plains' },
    { id: 26, name: 'temperate forests or underground' },
    { id: 27, name: 'any (Elemental Plane of Fire)' },
    { id: 28, name: 'temperate and warm land' },
    { id: 29, name: 'any (Plane of Fire)' },
    { id: 30, name: 'temperate forests and urban' },
    { id: 31, name: 'cold plains or mountains' },
    { id: 32, name: 'Any aquatic' },
    { id: 33, name: 'tropical coasts and rivers' },
    { id: 34, name: 'any (Ivory Labyrinth)' },
    { id: 35, name: 'temperate marshes or underground' },
    { id: 36, name: 'temperate lakes or rivers' },
    { id: 37, name: 'temperate or warm swamps' },
    { id: 38, name: 'temperate or cold hills' },
    { id: 39, name: 'temperate and warm water, and underground' },
    { id: 40, name: 'any' },
    { id: 41, name: 'any aquatic' },
    {
      id: 42,
      name: 'any (Elemental Plane of Earth, Elemental Plane of Fire, Plane of Molten Skies)',
    },
    { id: 43, name: 'temperate marshes, hills, or coasts' },
    { id: 44, name: 'any air (Nirvana)' },
    { id: 45, name: 'warm hills and mountains' },
    { id: 46, name: 'any temperate, warm, or urban' },
    { id: 47, name: 'temperate and warm marshes' },
    { id: 48, name: 'any temperate or warm land' },
    { id: 49, name: 'any (Ethereal Plane)' },
    { id: 50, name: 'any (graveyards, mausoleums, cemeteries)' },
    { id: 51, name: 'tropical swamps' },
    { id: 52, name: 'warm marshes or rivers' },
    { id: 53, name: 'temperate forest' },
    { id: 54, name: 'warm rivers' },
    { id: 55, name: 'temperate hills and plains' },
    { id: 56, name: 'any (Kurnugia)' },
    { id: 57, name: 'temperate forests and plains' },
    { id: 58, name: 'any (lower planes)' },
    { id: 59, name: 'temperate or warm forests' },
    { id: 60, name: 'Abyss, Gehenna, Hades, Nine Hells, or Tarterus' },
    { id: 61, name: 'temperate mountains or hills' },
    { id: 62, name: 'temperate forest or plains' },
    { id: 63, name: 'any liquid-based outer or inner plane' },
    { id: 64, name: 'any forests or swamps' },
    { id: 65, name: 'cold ruins' },
    { id: 66, name: 'warm desert and hills' },
    { id: 67, name: 'any (Elemental Plane of Earth)' },
    { id: 68, name: 'temperate or warm deserts or forests' },
    { id: 69, name: 'cold marshes and underground' },
    { id: 70, name: 'any swamps or underground' },
    { id: 71, name: 'any land and underground, lower planes' },
    { id: 72, name: 'any (primal land of fey)' },
    { id: 73, name: 'cold lakes and swamps' },
    { id: 74, name: 'temperate forest or marshes' },
    { id: 75, name: 'any (Hell)' },
    { id: 76, name: 'any (usually tombs)' },
    {
      id: 77,
      name: 'Sea of Fire (Plane of Fire and Plane of Molten Skies) Sea of Fire (Plane of Fire and Plane of Molten Skies)',
    },
    { id: 78, name: 'temperate and warm coastlines and underground' },
    { id: 79, name: 'any mountains' },
    { id: 80, name: 'warm oceans' },
    { id: 81, name: 'temperate mountain valleys' },
    { id: 82, name: 'temperate or warm land, aquatic, and underground' },
    {
      id: 83,
      name: 'warm or temperate deserts, forests, plains, or underground',
    },
    { id: 84, name: 'any temperate or warm forest or plains, or urban' },
    { id: 85, name: 'warm marshes' },
    { id: 86, name: 'Any' },
    { id: 87, name: 'cold forests and mountains' },
    { id: 88, name: 'warm forests, oceans, or rivers' },
    { id: 89, name: 'Quasi-Plane of Lightning' },
    { id: 90, name: 'Temperate or warm aquatic' },
    { id: 91, name: 'warm jungles and forests' },
    { id: 92, name: 'any warm land' },
    { id: 93, name: 'any swamps or woodlands' },
    { id: 94, name: 'any water (Nirvana)' },
    { id: 95, name: 'any oceans or coastlines' },
    { id: 96, name: 'warm forests' },
    { id: 97, name: 'warm deserts and hills' },
    { id: 98, name: 'Plane of Molten Skies' },
    { id: 99, name: 'any land or water (Plane of Water)' },
    { id: 100, name: 'any cold land' },
    { id: 101, name: 'cold hills and underground' },
    { id: 102, name: 'any forests, plains, and swamps' },
    { id: 103, name: 'Quasi-Plane of Acid' },
    { id: 104, name: 'temperate or warm forests and underground' },
    { id: 105, name: 'temperate and warm forest' },
    { id: 106, name: 'temperate ruins' },
    { id: 107, name: 'temperate or tropical forests or ruins' },
    { id: 108, name: 'any lawful evil-aligned plane' },
    { id: 109, name: 'any (Hell or Infernus)' },
    { id: 110, name: 'any lake or river' },
    { id: 111, name: 'temperate plains and forests and underground' },
    { id: 112, name: 'any hills or plains' },
    { id: 113, name: 'temperate or tropical forests' },
    { id: 114, name: 'temperate ruins or underground' },
    { id: 115, name: 'temperate plains, hills, or forests' },
    { id: 116, name: 'temperate forests or fresh water' },
    { id: 117, name: 'cold plains, forests, and marshes' },
    { id: 118, name: 'any underground or urban' },
    { id: 119, name: 'cold or temperate hills or mountains' },
    { id: 120, name: 'temperate forests and marshes' },
    { id: 121, name: 'warm or temperate forests' },
    { id: 122, name: 'any cold' },
    { id: 123, name: 'temperate forests, hills, mountains, or plains' },
    { id: 124, name: 'Astral Plane' },
    { id: 125, name: 'any (lawful plane)' },
    { id: 126, name: 'warm forests or marshes' },
    { id: 127, name: 'any (Plane of Air, Plane of Fire, or Plane of Smoke)' },
    { id: 128, name: 'any hills' },
    { id: 129, name: 'any coastal' },
    { id: 130, name: 'warm ruins' },
    { id: 131, name: 'temperate and warm plains' },
    { id: 132, name: 'warm lakes and rivers' },
    { id: 133, name: 'cold mountains or any' },
    { id: 134, name: 'cold or temperate forests and plains' },
    { id: 135, name: 'any (Nirvana)' },
    { id: 136, name: 'any (Purgatory)' },
    { id: 137, name: 'any (Positive Energy Plane)' },
    { id: 138, name: 'Plane of Fire' },
    { id: 139, name: 'temperate mountains and underground' },
    { id: 140, name: 'any (Spellscar Desert)' },
    { id: 141, name: 'any urban or plains' },
    { id: 142, name: 'any land (Plane of Earth)' },
    { id: 143, name: 'temperate or warm coastlines or forests' },
    { id: 144, name: 'warm lakes, rivers, or swamps' },
    { id: 145, name: 'any warm or hot' },
    { id: 146, name: 'warm forests or hills' },
    { id: 147, name: 'warm hills or mountains' },
    { id: 148, name: 'warm forest and mountains' },
    { id: 149, name: 'any evil-aligned plane' },
    { id: 150, name: 'Elemental Plane of Air' },
    { id: 151, name: 'warm plains and forests' },
    { id: 152, name: 'temperate marshes or plains' },
    { id: 153, name: 'any forests' },
    { id: 154, name: 'any rivers' },
    { id: 155, name: 'Northlands forests and plains' },
    { id: 156, name: 'ocean' },
    { id: 157, name: 'temperate mountains' },
    { id: 158, name: 'any aquatic (Plane of Water)' },
    { id: 159, name: 'cold plains and underground' },
    { id: 160, name: 'any (Elysium)' },
    { id: 161, name: 'temperate forests or mountains' },
    { id: 162, name: 'any warm land and underground' },
    { id: 163, name: 'temperate or warm marshes' },
    { id: 164, name: 'outer space or cold forest' },
    { id: 165, name: 'any good-aligned plane' },
    { id: 166, name: 'any underground' },
    { id: 167, name: 'any underground (Plane of Earth)' },
    { id: 168, name: 'warm plains or deserts (the Mana Wastes)' },
    { id: 169, name: 'temperate forest and hills' },
    { id: 170, name: 'temperate hills or mountains' },
    { id: 171, name: 'any except true neutral' },
    { id: 172, name: 'temperate or warm hills or mountains' },
    { id: 173, name: 'warm and temperate fresh water and swamps' },
    { id: 174, name: 'temperate or warm water' },
    { id: 175, name: 'any land (Plane of Shadow)' },
    { id: 176, name: 'temperate or tropical hills' },
    { id: 177, name: 'temperate deserts' },
    { id: 178, name: 'any (Aucturn)' },
    { id: 179, name: 'temperate hills, mountains, or underground' },
    { id: 180, name: 'any coastlines' },
    { id: 181, name: 'cold lands' },
    { id: 182, name: 'temperate forest, swamp, or underground' },
    { id: 183, name: 'any (Shadow Plane)' },
    { id: 184, name: 'any freshwater' },
    { id: 185, name: 'temperate and warm mountains' },
    { id: 186, name: 'warm rivers (Garund)' },
    { id: 187, name: 'any (Plane of Shadow)' },
    { id: 188, name: 'underground and temperate marshes' },
    { id: 189, name: 'any coastlines or water' },
    { id: 190, name: 'any temperate and warm and underground' },
    { id: 191, name: 'any mountains or underground (Plane of Fire)' },
    { id: 192, name: 'temperate freshwater' },
    { id: 193, name: 'Positive Energy Plane' },
    { id: 194, name: 'any oceans (Abyss)' },
    { id: 195, name: 'temperate hills or plains' },
    { id: 196, name: 'swamp or underground' },
    { id: 197, name: 'any (Quantium)' },
    { id: 198, name: 'temperate or cold aquatic' },
    { id: 199, name: 'warm mountains or deserts' },
    { id: 200, name: 'temperate forests' },
    { id: 201, name: 'warm coastal regions' },
    { id: 202, name: 'marshes' },
    { id: 203, name: 'warm or temperate land or underground' },
    { id: 204, name: 'any land (Elysium)' },
    { id: 205, name: 'temperate coastlines' },
    { id: 206, name: 'temperate and warm deserts' },
    { id: 207, name: 'cold forests or mountains' },
    { id: 208, name: 'any temperate or warm' },
    { id: 209, name: 'astral plane' },
    {
      id: 210,
      name: 'any (Elemental Plane of Air or Quasi- Elemental Plane of Lightning)',
    },
    { id: 211, name: 'any (Castrovel)' },
    { id: 212, name: 'any (the Abyss)' },
    { id: 213, name: 'any (Plane of Air)' },
    { id: 214, name: 'warm or temperate oceans' },
    {
      id: 215,
      name: 'Sea of Fire (Elemental Plane of Fire or Plane of Molten Skies)',
    },
    { id: 216, name: 'any (Hell or Ethereal Plane)' },
    { id: 217, name: 'temperate and warm forests and underground' },
    { id: 218, name: 'cold or temperate hills' },
    { id: 219, name: 'any land (Field of Maidens)' },
    { id: 220, name: 'Aballon' },
    { id: 221, name: 'any (Nex)' },
    { id: 222, name: 'temperate hills, plains, or forests' },
    { id: 223, name: 'cold forests or plains' },
    { id: 224, name: 'cold plains, hills and mountains' },
    { id: 225, name: 'warm deserts or underground' },
    { id: 226, name: 'temperate plains' },
    { id: 227, name: 'any ruins' },
    { id: 228, name: 'urban' },
    { id: 229, name: 'temperate plains or forests' },
    { id: 230, name: 'warm hills' },
    { id: 231, name: 'any hills or forests' },
    { id: 232, name: 'tropical hills and mountains' },
    { id: 233, name: 'cold aquatic or underground' },
    { id: 234, name: 'temperate or cold forests' },
    { id: 235, name: 'warm forests or plains' },
    { id: 236, name: 'temperate and warm forests and aquatic' },
    { id: 237, name: 'cold oceans' },
    { id: 238, name: 'temperate forests, hills, or mountains' },
    { id: 239, name: 'tropical jungles' },
    { id: 240, name: 'underground' },
    { id: 241, name: 'warm deserts or mountains' },
    { id: 242, name: 'warm or temperate water or coastlines' },
    { id: 243, name: 'any (Nine Hells)' },
    { id: 244, name: 'temperate and warm forests and marshes' },
    { id: 245, name: 'temperate or warm hills' },
    { id: 246, name: 'warm land' },
    { id: 247, name: 'any swamps' },
    { id: 248, name: 'temperate plains or hills' },
    { id: 249, name: 'temperate or warm oceans or coastlines' },
    { id: 250, name: 'cold lakes, plains, or oceans' },
    { id: 251, name: 'cold forest and plains' },
    { id: 252, name: 'temperate forests and hills' },
    { id: 253, name: 'temperate swamps or underground' },
    { id: 254, name: 'warm jungles and swamps' },
    { id: 255, name: 'temperate coast or forest' },
    { id: 256, name: 'temperate or cold forests and marshes' },
    { id: 257, name: 'warm plains or coastlines' },
    { id: 258, name: 'Quasi-Elemental Plane of Lightning' },
    { id: 259, name: 'cold forests' },
    { id: 260, name: 'warm forests, hills, mountains, and plains' },
    { id: 261, name: 'cold or temperate coasts, hills, or marshes' },
    { id: 262, name: 'any temperate' },
    { id: 263, name: 'warm and temperate plains' },
    { id: 264, name: 'warm deserts, plains, or hills' },
    { id: 265, name: 'temperate rivers or streams' },
    { id: 266, name: "any (R'lyeh)" },
    { id: 267, name: 'any oceans' },
    { id: 268, name: 'any (Tarterus)' },
    { id: 269, name: 'temperate skies, hills, and mountains' },
    { id: 270, name: 'warm aquatic' },
    { id: 271, name: 'warm forests and plains or underground' },
    { id: 272, name: 'warm deserts' },
    { id: 273, name: 'cold plains and hills' },
    { id: 274, name: 'temperate and warm forests and swamps' },
    { id: 275, name: 'any plains or forests' },
    { id: 276, name: 'Hades' },
    { id: 277, name: 'Inner and Outer planes' },
    { id: 278, name: 'underground or temperate and warm swamps' },
    { id: 279, name: 'warm plains and underground' },
    { id: 280, name: 'any water' },
    { id: 281, name: 'temperate hills and underground' },
    { id: 282, name: 'temperate forests, hills, and mountains' },
    { id: 283, name: 'temperate and warm marshes and underground' },
    { id: 284, name: 'temperate hills and ruins' },
    { id: 285, name: 'cold or temperate water (waterfalls)' },
    { id: 286, name: 'temperate and warm aquatic' },
    { id: 287, name: 'temperate or warm aquatic' },
    { id: 288, name: 'temperate or warm ocean or coastline' },
    { id: 289, name: 'any oceans (during storms)' },
    { id: 290, name: 'temperate and warm lands and underground' },
    { id: 291, name: 'warm hills or plains' },
    { id: 292, name: 'temperate and warm marshes and rivers' },
    { id: 293, name: 'River Styx' },
    { id: 294, name: 'warm forests or swamps' },
    { id: 295, name: 'any land (lawful plane)' },
    { id: 296, name: 'any land (usually jungles or underground)' },
    { id: 297, name: 'any Outer Plane (Abaddon)' },
    { id: 298, name: 'warm forests and marshes' },
    { id: 299, name: 'cold and temperate forests, hills and plains' },
    { id: 300, name: 'warm aquatic and plains' },
    { id: 301, name: 'Hell' },
    { id: 302, name: 'any land' },
    { id: 303, name: 'cold coastlines and plains' },
    { id: 304, name: 'temperate and warm hills and mountains' },
    { id: 305, name: 'temperate and warm forests, underground, and urban' },
    { id: 306, name: 'any urban or ruins' },
    { id: 307, name: 'any forests or plains' },
    { id: 308, name: 'warm plains (Nuat)' },
    { id: 309, name: 'any warm' },
    { id: 310, name: 'Elemental Plane of Fire' },
    { id: 311, name: 'any hills or mountains' },
    { id: 312, name: 'temperate or warm forests or plains' },
    { id: 313, name: 'Nine Hells' },
    { id: 314, name: 'warm plains and shorelines' },
    { id: 315, name: 'temperate or warm plains' },
    { id: 316, name: 'cold deserts and glaciers' },
    { id: 317, name: 'any (extraplanar)' },
    { id: 318, name: 'warm hills and deserts' },
    { id: 319, name: 'temperate and warm forest and underground' },
    { id: 320, name: 'cold hills and moutains' },
    { id: 321, name: 'Gehenna, Hades, or Tarterus' },
    { id: 322, name: 'temperate or warm forests or coasts' },
    { id: 323, name: 'temperate and warm forests' },
    { id: 324, name: 'temperate or warm deserts or plains' },
    { id: 325, name: 'any marsh' },
    { id: 326, name: 'temperate and warm forest, hill, marsh, and plains' },
    { id: 327, name: "warm jungles (Yoha's Graveyard)" },
    { id: 328, name: 'any deserts or oceans' },
    { id: 329, name: 'cold mountains' },
    { id: 330, name: 'cold rivers' },
    { id: 331, name: 'any (Heaven)' },
    { id: 332, name: 'any mountains or underground' },
    { id: 333, name: 'any forest or plain (Elysium)' },
    { id: 334, name: 'warm or temperate aquatic' },
    { id: 335, name: 'temperate forests and plains or underground' },
    { id: 336, name: 'warm desert' },
    { id: 337, name: 'warm marshes and aquatic' },
    { id: 338, name: 'temperate plains and underground' },
    { id: 339, name: 'any underground (beneath Kaer Maga)' },
    { id: 340, name: 'warm forests and swamps' },
    { id: 341, name: 'temperate or warm swamps or underground' },
    { id: 342, name: 'Plane of Molten Skies, Elemental Plane of Fire' },
    { id: 343, name: 'any rivers or marshes' },
    { id: 344, name: 'any (Worldwound)' },
    { id: 345, name: 'temperate desert' },
    { id: 346, name: 'temperate islands' },
    { id: 347, name: 'any (Astral Plane)' },
    { id: 348, name: 'warm jungle' },
    { id: 349, name: 'warm coastline, swamps, or plains' },
    { id: 350, name: 'any temperate land' },
    { id: 351, name: 'any underground (except water)' },
    { id: 352, name: 'any (Vista)' },
    { id: 353, name: 'temperate or warm forest or underground' },
    { id: 354, name: 'any (Korvosa)' },
    { id: 355, name: 'any water or coastlines' },
    { id: 356, name: 'temperate forests and mountains' },
    { id: 357, name: 'any blighted land' },
    { id: 358, name: 'any ruins or underground' },
    { id: 359, name: 'any tropical (First World)' },
    { id: 360, name: 'Outer Planes' },
    { id: 361, name: 'any (Quasi-Elemental Plane of Lightning)' },
    { id: 362, name: 'Limbo' },
    { id: 363, name: 'any (Plane of Air or Plane of Water)' },
    { id: 364, name: 'any saltwater' },
    { id: 365, name: 'any aquatic or land' },
    { id: 366, name: 'warm forests or underground' },
    { id: 367, name: 'any (usually Gehenna, Hades, or Tarterus)' },
    { id: 368, name: 'warm jungles (Mwangi Expanse)' },
    { id: 369, name: 'elemental plane of fire' },
    { id: 370, name: 'cold and temperate aquatic' },
    { id: 371, name: 'temperate or tropical forests or hills' },
    { id: 372, name: 'any wastelands' },
    { id: 373, name: 'any land (Irrisen)' },
    { id: 374, name: 'Plane of Air' },
    { id: 375, name: 'temperate or cold ocean' },
    { id: 376, name: 'any (Abyss; volcanic regions)' },
    { id: 377, name: 'tropical forests (Mediogalti Island)' },
    { id: 378, name: 'any land, aquatic, and underground' },
    { id: 379, name: 'any non-cold' },
    { id: 380, name: 'cold deserts or mountains' },
    { id: 381, name: 'temperate hills or underground' },
    { id: 382, name: 'any waters (Nirvana)' },
    { id: 383, name: 'temperate plains and forests' },
    { id: 384, name: 'any ocean' },
    { id: 385, name: 'any land or underground near cities' },
    { id: 386, name: 'any forest and hills' },
    { id: 387, name: 'warm coastline' },
    { id: 388, name: 'temperate swamps' },
    { id: 389, name: 'temperate underground or marshes' },
    { id: 390, name: 'any land (Nirvana)' },
    { id: 391, name: 'any land (extraplanar)' },
    { id: 392, name: 'outer planes' },
    { id: 393, name: 'temperate oceans' },
    { id: 394, name: 'warm forests (Abyss)' },
    { id: 395, name: 'any (Abaddon)' },
    { id: 396, name: 'volcanic underground' },
    { id: 397, name: 'warm swamps' },
    { id: 398, name: 'warm plains or hills' },
    { id: 399, name: 'Elemental Plane of Earth' },
    { id: 400, name: 'temperate forests, hills, or plains (pumpkin patches)' },
    { id: 401, name: 'temperate lakes, rivers, or swamps' },
    { id: 402, name: 'cold or temperate water or underground' },
    { id: 403, name: 'temperate mountains and coastal islands' },
    { id: 404, name: 'Para-Elemental Plane of Heat' },
    { id: 405, name: 'warm rivers or marshes' },
    { id: 406, name: 'temperate underground or deep forest' },
    { id: 407, name: 'any (Darklands)' },
    { id: 408, name: 'cold volcanic mountains' },
    { id: 409, name: 'Plane of Time' },
    { id: 410, name: 'Elemental Plane of Fire or Plane of Molten Skies' },
    { id: 411, name: 'temperate forests or plains' },
    { id: 412, name: 'temperate and warm deserts and mountains' },
    { id: 413, name: 'temperate or warm ocean' },
    { id: 414, name: 'Any forest, hills, plains, and mountains' },
    { id: 415, name: 'any forest, hill, jungle, or plains' },
    { id: 416, name: 'any (see text)' },
    { id: 417, name: 'tropical rivers and lakes' },
    { id: 418, name: 'any forests (primal land of fey)' },
    { id: 419, name: 'any land or urban' },
    { id: 420, name: 'any terrestrial vacuum' },
    { id: 421, name: 'forests or jungle' },
    { id: 422, name: 'any (Negative Energy Plane)' },
    { id: 423, name: 'warm hills and marshes' },
    { id: 424, name: 'any swamp' },
    { id: 425, name: 'warm islands' },
    { id: 426, name: 'temperate and cold forests' },
    { id: 427, name: 'Quasi-Plane of Obsidian' },
    { id: 428, name: 'warm lakes' },
    { id: 429, name: 'warm forests and mountains' },
    { id: 430, name: 'warm forests and hills' },
    { id: 431, name: 'temperate marshes' },
    { id: 432, name: 'temperate or warm rivers' },
    { id: 433, name: 'any oceans and underground' },
    { id: 434, name: 'temperate water' },
    { id: 435, name: 'any temperate and warm land' },
    { id: 436, name: 'any cold (Abyss)' },
    { id: 437, name: 'any (Material Plane only)' },
    { id: 438, name: 'Plane of Earth' },
    { id: 439, name: 'any aboveground natural area' },
    { id: 440, name: 'warm forests, hills, or mountains' },
    { id: 441, name: 'any (Outer Planes)' },
    { id: 442, name: 'warm ocean or coastline' },
    { id: 443, name: 'Plane of Slime' },
    { id: 444, name: 'any land or water' },
    { id: 445, name: 'temperate swamp' },
    { id: 446, name: 'warm forests, hills, or plains' },
    { id: 447, name: 'any (Plane of Molten Skies)' },
    { id: 448, name: 'cold hills' },
    { id: 449, name: 'cold hills and mountains' },
    { id: 450, name: 'any (underground)' },
    { id: 451, name: 'any forest' },
    { id: 452, name: 'warm forest and aquatic' },
    { id: 453, name: 'any cold or temperate land' },
    { id: 454, name: 'cold hills, mountains, or plains' },
    { id: 455, name: 'any volcano or underground' },
    { id: 456, name: 'temperate forests, marshes, and urban' },
    { id: 457, name: 'temperate hills' },
    { id: 458, name: 'see text' },
    { id: 459, name: 'temperate and hot plains or urban' },
    { id: 460, name: 'temperate or warm oceans' },
    { id: 461, name: 'any (Casmaron)' },
    { id: 462, name: 'warm deserts or hills' },
    { id: 463, name: 'any temperate and warm' },
    { id: 464, name: 'temperate lakes or swamps' },
    { id: 465, name: 'warm coastline or forest' },
    { id: 466, name: 'any land or underground (Plane of Shadow)' },
    { id: 467, name: 'warm water' },
    { id: 468, name: 'warm rivers and marshes' },
    { id: 469, name: 'any land (Plane of Fire)' },
    { id: 470, name: 'aquatic' },
    { id: 471, name: 'any plains or swamps' },
    { id: 472, name: 'any (Infernus)' },
    { id: 473, name: 'any mountain' },
    { id: 474, name: 'Negative Energy Plane' },
    { id: 475, name: 'temperate forests or jungles' },
    { id: 476, name: 'cold swamps or coastlines' },
    { id: 477, name: 'warm coasts and oceans' },
    { id: 478, name: 'temperate or warm forests or swamps' },
    { id: 479, name: 'warm plains or desert' },
    { id: 480, name: 'warm mountains' },
    { id: 481, name: 'Elysium' },
    { id: 482, name: 'Plane of Shadow' },
    { id: 483, name: 'cold and temperate forests, marshes and plains' },
    { id: 484, name: 'underground or temperate forest' },
    { id: 485, name: 'warm forests, swamps, and fresh water' },
    { id: 486, name: 'warm deserts or urban' },
    { id: 487, name: 'warm deserts or islands' },
    { id: 488, name: 'temperate hills and mountains' },
    { id: 489, name: 'cold forest or mountains' },
    { id: 490, name: 'temperate coasts' },
    { id: 491, name: 'cold coastlines' },
    { id: 492, name: 'temperate rivers or lakes' },
    { id: 493, name: 'Plane of Water' },
    { id: 494, name: 'any underground (Darklands)' },
    { id: 495, name: 'any (the Boneyard)' },
    { id: 496, name: 'cold forests and plains' },
    { id: 497, name: 'Temperate Forests' },
    { id: 498, name: 'Elemental Plane of Time' },
    { id: 499, name: 'warm plains' },
    { id: 500, name: 'any urban or underground' },
    { id: 501, name: 'cold coastlines, hills, or plains' },
    { id: 502, name: 'temperate forest or swamp' },
    { id: 503, name: 'temperate marshes and underground' },
    { id: 504, name: 'any (Abyss; battlefields and graveyards)' },
    { id: 505, name: 'any land (evil Outer Plane)' },
    { id: 506, name: 'temperate or warm forests, hills, or underground' },
    { id: 507, name: 'any forests or mountains (Nirvana)' },
    { id: 508, name: 'cold hills or glaciers' },
    { id: 509, name: 'temperate aquatic' },
    { id: 510, name: 'temperate land' },
    { id: 511, name: 'any land (Hell)' },
    { id: 512, name: 'temperate and warm swamps' },
    { id: 513, name: 'cold mountains or underground' },
    { id: 514, name: 'any (usually underground)' },
    { id: 515, name: 'any relatively flat and dry terrain' },
    { id: 516, name: 'any freshwater aquatic' },
    { id: 517, name: 'temperate and warm oceans' },
    { id: 518, name: 'any lakes' },
    { id: 519, name: 'underground (the Bloodways)' },
    { id: 520, name: 'temperate mountains or urban' },
    { id: 521, name: 'warm deserts, hills, or plains' },
    { id: 522, name: 'temperate and hot forests and deserts' },
    { id: 523, name: 'Quasi-Plane of Vapor' },
    { id: 524, name: 'temperate forests or hills' },
    { id: 525, name: 'temperate or cold aquatic or underground' },
    { id: 526, name: 'cold mountainous coastlines' },
    { id: 527, name: 'warm forest and plains' },
    { id: 528, name: 'any marshes or underground' },
    { id: 529, name: 'cold or temperate plains' },
    { id: 530, name: 'any battle' },
    { id: 531, name: 'temperate or warm forest' },
    { id: 532, name: 'cold and temperate forests and plains' },
    { id: 533, name: 'any temperate or warm aquatic' },
    { id: 534, name: 'warm or temperate plains' },
    { id: 535, name: 'tropical oceans' },
    { id: 536, name: 'any sky' },
    { id: 537, name: 'temperate or tropical swamps' },
    { id: 538, name: 'warm forest' },
    { id: 539, name: 'any swamp or underground' },
    { id: 540, name: 'vacuum' },
    { id: 541, name: 'temperate forests (The Hollow Mountain)' },
    { id: 542, name: 'warm mountains or underground' },
    { id: 543, name: 'any swamp (Abyss)' },
    { id: 544, name: 'warm subterranean lakes and rivers' },
    { id: 545, name: 'any (evil planes)' },
    { id: 546, name: 'temperate or warm jungles' },
    { id: 547, name: 'any tropical' },
    { id: 548, name: 'any (usually Gehenna, Tarterus, or Hades)' },
    { id: 549, name: 'any underground or swamps' },
    { id: 550, name: 'temperate forests or urban' },
    { id: 551, name: 'any (Abaddon or Astral Plane)' },
    { id: 552, name: 'temperate and warm plains or desert' },
    { id: 553, name: 'temperate or warm water or shore' },
    { id: 554, name: 'any land and underground' },
    { id: 555, name: 'any (Plane of Earth)' },
    { id: 556, name: 'any forests or hills' },
    { id: 557, name: 'cold plains' },
    { id: 558, name: 'any mountains (Dimension of Dreams)' },
    { id: 559, name: 'temperate or cold hills or underground' },
    { id: 560, name: 'cold or temperate forests and mountains' },
    { id: 561, name: 'cold forests, hills, mountains and plains' },
    { id: 562, name: 'any ocean or coastline' },
    { id: 563, name: 'cold and temperate oceans' },
    { id: 564, name: 'any evil-aligned planes' },
    { id: 565, name: 'any temperate or underground' },
    { id: 566, name: 'warm mountains and underground' },
    { id: 567, name: 'cold or temperate forest and plains' },
    { id: 568, name: 'warm coasts or forests' },
    { id: 569, name: 'temperate forest and plains (usually coastal regions)' },
    { id: 570, name: 'any forest or hill' },
    { id: 571, name: 'any underground (the Abyss)' },
    { id: 572, name: 'The Abyss' },
    { id: 573, name: 'temperate ocean' },
    { id: 574, name: 'temperate or warm land' },
    { id: 575, name: 'cold swamps' },
    { id: 576, name: 'any land (Abaddon)' },
    { id: 577, name: 'temperate marsh' },
    { id: 578, name: 'warm plains and deserts' },
    { id: 579, name: 'any land (graveyards and cemeteries)' },
    { id: 580, name: 'any temperate and warm land and underground' },
    { id: 581, name: 'warm forest, plains, or hills' },
    { id: 582, name: 'temperate or warm marshes or underground' },
    { id: 583, name: 'any (graveyards or the Boneyard)' },
    { id: 584, name: 'warm fresh water' },
    { id: 585, name: 'Plane of Molten Skies or Elemental Plane of Fire' },
    { id: 586, name: 'any water (Plane of Water)' },
    { id: 587, name: 'temperate forests, plains, or swamps' },
    { id: 588, name: 'cold and temperate forests' },
    { id: 589, name: 'tropical jungles (Mediogalti Island)' },
    { id: 590, name: 'warm forests or mountains' },
    { id: 591, name: 'Plane of Gravity' },
    { id: 592, name: 'warm forests and plains' },
    { id: 593, name: 'any (the Worldwound)' },
    { id: 594, name: 'temperate or warm forests or underground' },
    { id: 595, name: 'any temperate or tropical' },
    { id: 596, name: 'warm deserts or plains' },
    { id: 597, name: 'any (haunted sites or ruins)' },
    { id: 598, name: 'cold plains, hills, or mountains' },
    { id: 599, name: 'gas giants or vacuum' },
    { id: 600, name: 'any (River Styx)' },
    { id: 601, name: 'warm oceans or coastlines' },
    { id: 602, name: 'any land or sky (lightning storms)' },
    { id: 603, name: 'any (Sekatar-Seraktis)' },
    { id: 604, name: 'warm rivers, lakes, and swamps' },
    { id: 605, name: 'temperate or warm forests and marshes' },
    { id: 606, name: 'any land or underground' },
    { id: 607, name: 'tropical forests and jungles' },
    { id: 608, name: 'temperate forest and mountain' },
    { id: 609, name: 'any (Ghahazi, Abyss)' },
    { id: 610, name: 'any volcanoes or underground' },
    { id: 611, name: 'temperate forests or marshes' },
    { id: 612, name: 'cold marshes' },
    { id: 613, name: 'tropical lakes and rivers' },
    { id: 614, name: 'temperate forests, mountains, or underground' },
    { id: 615, name: 'any non-cold underground' },
    { id: 616, name: 'any marsh or underground' },
    { id: 617, name: 'any air' },
    { id: 618, name: 'any urban' },
    { id: 619, name: 'temperate or warm mountains' },
    { id: 620, name: 'any (Abyss)' },
    { id: 621, name: 'warm coastlines' },
    { id: 622, name: 'any water (coastal)' },
    { id: 623, name: 'warm ocean' },
    { id: 624, name: 'urban (Abyss)' },
    { id: 625, name: 'temperate swamp or underground' },
    { id: 626, name: 'any (elemental planes)' },
    { id: 627, name: 'any (Plane of Water)' },
    { id: 628, name: 'any near ghouls' },
    { id: 629, name: 'tropical deserts' },
    { id: 630, name: 'any land or water (Plane of Earth)' },
    { id: 631, name: 'tropical or temperate forests' },
    { id: 632, name: 'cold or temperate forests' },
    { id: 633, name: 'temperate forests, lakes, or rivers' },
    { id: 634, name: 'warm jungles' },
    { id: 635, name: 'cold hills or mountains' },
    { id: 636, name: 'any land (Abyss)' },
    { id: 637, name: 'temperate mountains (Arcadia)' },
  ];

  return (
    <div>
      <label htmlFor="">Environment</label>
      <input
        type="text"
        name="environment"
        onChange={(e) => onEnvironmentChange(e)}
      />
    </div>
  );
}

export default Environment;
