function Subtype({ onSubtypeChange }) {
  let subtypeOptions = {
    0: 'aquatic',
    1: 'ratfolk',
    2: 'clockwork',
    3: 'augmented aberration',
    4: 'orc',
    5: 'swarm',
    6: 'sciruian',
    7: 'shapechanger',
    8: 'fire',
    9: 'gnoll',
    10: 'azata',
    11: 'reptilian',
    12: 'sasquatch',
    13: 'agathion',
    14: 'giant',
    15: 'lashunta',
    16: 'tengu',
    17: 'good',
    18: 'augmented humanoid',
    19: 'changeling',
    20: 'oni',
    21: 'asura',
    22: 'null',
    23: 'elemental',
    24: 'mythic',
    25: 'kuru',
    26: 'wayang',
    27: 'stormwarden',
    28: 'amphibious',
    29: 'lupin',
    30: 'strix',
    31: 'augmented animal',
    32: 'div',
    33: 'varies',
    34: 'dwarf ',
    35: 'behemoth',
    36: 'tabaxi',
    37: 'incorporeal',
    38: 'time',
    39: 'augmented human',
    40: 'ogrillon',
    41: 'water',
    42: 'leshy',
    43: 'horde',
    44: 'archon',
    45: 'earth',
    46: 'extraplanar',
    47: 'kitsune',
    48: 'kasatha',
    49: 'augmented fey',
    50: 'charau-ka',
    51: 'augmented magical beast',
    52: 'kuah-lij',
    53: 'xothotak',
    54: 'skulk',
    55: 'dark folk',
    56: 'samsaran',
    57: 'elf ',
    58: 'colossus',
    59: 'aquatic*',
    60: 'Water',
    61: 'elf',
    62: 'aeon',
    63: 'dhampir',
    64: 'daemon',
    65: 'native',
    66: 'goblinoid',
    67: 'acid',
    68: 'human',
    69: 'vanara',
    70: 'Triaxian',
    71: 'gnome',
    72: 'chaotic',
    73: 'Fire',
    74: 'korog',
    75: 'boggard',
    76: 'devil',
    77: 'angel',
    78: 'air',
    79: 'fungus',
    80: 'cold',
    81: 'vishkanya',
    82: 'derro',
    83: 'psychopomp',
    84: 'ogren',
    85: 'android',
    86: 'kami',
    87: 'syrinx',
    88: 'megaswarm',
    89: 'augmented vermin',
    90: 'adlet',
    91: 'evil',
    92: 'electricity',
    93: 'grippli',
    94: 'catfolk',
  };

  return (
    <div>
      <label htmlFor="subtype">subtype</label>
      <input type="text" name="subtype" onChange={(e) => onSubtypeChange(e)} />
    </div>
  );
}

export default Subtype;
