function Subtype({ onSubtypeChange }) {
  let subtypeOptions = [
    { id: 0, name: 'aquatic' },
    { id: 1, name: 'ratfolk' },
    { id: 2, name: 'clockwork' },
    { id: 3, name: 'augmented aberration' },
    { id: 4, name: 'orc' },
    { id: 5, name: 'swarm' },
    { id: 6, name: 'sciruian' },
    { id: 7, name: 'shapechanger' },
    { id: 8, name: 'fire' },
    { id: 9, name: 'gnoll' },
    { id: 10, name: 'azata' },
    { id: 11, name: 'reptilian' },
    { id: 12, name: 'sasquatch' },
    { id: 13, name: 'agathion' },
    { id: 14, name: 'giant' },
    { id: 15, name: 'lashunta' },
    { id: 16, name: 'tengu' },
    { id: 17, name: 'good' },
    { id: 18, name: 'augmented humanoid' },
    { id: 19, name: 'changeling' },
    { id: 20, name: 'oni' },
    { id: 21, name: 'asura' },
    { id: 22, name: 'null' },
    { id: 23, name: 'elemental' },
    { id: 24, name: 'mythic' },
    { id: 25, name: 'kuru' },
    { id: 26, name: 'wayang' },
    { id: 27, name: 'stormwarden' },
    { id: 28, name: 'amphibious' },
    { id: 29, name: 'lupin' },
    { id: 30, name: 'strix' },
    { id: 31, name: 'augmented animal' },
    { id: 32, name: 'div' },
    { id: 33, name: 'varies' },
    { id: 34, name: 'dwarf ' },
    { id: 35, name: 'behemoth' },
    { id: 36, name: 'tabaxi' },
    { id: 37, name: 'incorporeal' },
    { id: 38, name: 'time' },
    { id: 39, name: 'augmented human' },
    { id: 40, name: 'ogrillon' },
    { id: 41, name: 'water' },
    { id: 42, name: 'leshy' },
    { id: 43, name: 'horde' },
    { id: 44, name: 'archon' },
    { id: 45, name: 'earth' },
    { id: 46, name: 'extraplanar' },
    { id: 47, name: 'kitsune' },
    { id: 48, name: 'kasatha' },
    { id: 49, name: 'augmented fey' },
    { id: 50, name: 'charau-ka' },
    { id: 51, name: 'augmented magical beast' },
    { id: 52, name: 'kuah-lij' },
    { id: 53, name: 'xothotak' },
    { id: 54, name: 'skulk' },
    { id: 55, name: 'dark folk' },
    { id: 56, name: 'samsaran' },
    { id: 57, name: 'elf ' },
    { id: 58, name: 'colossus' },
    { id: 59, name: 'aquatic*' },
    { id: 60, name: 'Water' },
    { id: 61, name: 'elf' },
    { id: 62, name: 'aeon' },
    { id: 63, name: 'dhampir' },
    { id: 64, name: 'daemon' },
    { id: 65, name: 'native' },
    { id: 66, name: 'goblinoid' },
    { id: 67, name: 'acid' },
    { id: 68, name: 'human' },
    { id: 69, name: 'vanara' },
    { id: 70, name: 'Triaxian' },
    { id: 71, name: 'gnome' },
    { id: 72, name: 'chaotic' },
    { id: 73, name: 'Fire' },
    { id: 74, name: 'korog' },
    { id: 75, name: 'boggard' },
    { id: 76, name: 'devil' },
    { id: 77, name: 'angel' },
    { id: 78, name: 'air' },
    { id: 79, name: 'fungus' },
    { id: 80, name: 'cold' },
    { id: 81, name: 'vishkanya' },
    { id: 82, name: 'derro' },
    { id: 83, name: 'psychopomp' },
    { id: 84, name: 'ogren' },
    { id: 85, name: 'android' },
    { id: 86, name: 'kami' },
    { id: 87, name: 'syrinx' },
    { id: 88, name: 'megaswarm' },
    { id: 89, name: 'augmented vermin' },
    { id: 90, name: 'adlet' },
    { id: 91, name: 'evil' },
    { id: 92, name: 'electricity' },
    { id: 93, name: 'grippli' },
    { id: 94, name: 'catfolk' },
  ];

  return (
    <div>
      <label htmlFor="subtype">subtype</label>
      <input type="text" name="subtype" onChange={(e) => onSubtypeChange(e)} />
    </div>
  );
}

export default Subtype;
